export default {
    name:'personalinfo',
    title:'Personalinfo',
    type:'document',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string'
        },
        {
            name:'email',
            title:'Email',
            type:'string'
        },
        {
            name:'phone',
            title:'Phone',
            type:'number'
        },
        {
            name:'resume',
            title:'Resume',
            type:'string'
        },
        {
            name:'title',
            title:'Title',
            type:'string'
        },
        {
            name:'github',
            title:'Github',
            type:'string'
        },
        {
            name:'linkedin',
            title:'Linkedin',
            type:'string'
        }
        
    ]
}